# COGS 108 - Data Checkpoint

## Authors

- Al Mazlo: Background research, Data curation, Writing - review & editing
- Angela Wu: Conceptualization, Data curation
- Sofina Yang: Conceptualization, Data curation
- Alyssia Almanza: Conceptualization, Data curation

## Research Question

How does public transportation usage (buses and metro), smoking prevalence rates, and electric vehicle (EV) adoption influence air quality and the rate of reported asthma attacks among asthma patients in Houston, San Francisco, and New York City?

## Background and Prior Work

### Background:
Air pollution is one of the leading environmental health risks worldwide, and urban transportation is a major contributor. Private vehicles, such as cars, trucks, and motorcycles, emit pollutants such as particulate matter (PM2.5 and PM10), nitrogen dioxide (NO2), carbon monoxide (CO), and volatile organic compounds (VOCs), all of which have been strongly linked to respiratory diseases, including asthma and chronic obstructive pulmonary disease (COPD). (1, 2)

From the report of Asthma and Allergy Foundation of America (5), poor air quality can negatively affect everyone’s health. Research shows that air pollution can make asthma worse and trigger asthma symptoms. Air pollution includes gases, smoke from fires, volcanic ash, dust particles, emissions from transportation, and other substances that can harm the lungs.

As cities grow, the concentration of vehicles increases, intensifying both traffic congestion and emissions, which has direct implications for public health. Understanding the link between transportation and air quality is crucial for policy-making aimed at improving population health.

Public transportation, such as buses, metros, and high-speed rail (HSR), has long been proposed as a solution to reduce private vehicle use. Expanding public transit can enable ease of movement for lower-income individuals while lowering urban air pollution by reducing congestion and moving more people collectively without increasing operational emissions per person. (3)

Other factors besides transportation also influence urban air quality and lung health, including smoking rates and adoption of EVs, which can have both positive and negative effects.

Our project aims to specifically observe the link between public transportation systems and air quality and lung disease, controlling for the factors mentioned above. Some of the cities we will investigate include Houston, New York City, and San Francisco.

It is important to note that our study is observational and relies on publicly available datasets, so we cannot definitively prove causation between public transportation and air quality. Many of the factors mentioned above are interrelated, and unobservable variables may influence the results. To mitigate bias, we will examine multiple cities and control for known confounding factors as carefully as possible, aiming to produce robust, evidence-based insights.


### Prior Work:
A relevant prior work is the technical report *Assessing the Impact of Air Pollution on Public Health along Transit Routes*, which examines how transportation and socioeconomic factors influence respiratory health in some major metropolitan areas, Dallas-Fort Worth and LA. The researchers applied stat techniques such as PCA and OLS to identify predictors of respiratory disease. Their findings showed strong correlations between both demographics and access to transit/automobile access to respiratory disease risk. Interestingly, populations with higher transit access were more prone to respiratory diseases. This work relates closely to our proposed project because it demonstrates a clear connection between transportation systems, air quality, and respiratory health. (3)

Another study published in Environmental Health Perspectives investigated the association between traffic-related air pollution and the incidence of asthma in children living near major roadways. The researchers found that exposure to combustion-related pollutants such as nitrogen dioxide (NO2) and ozone was significantly linked to increases in asthma prevalence among children at home and school environments. By analyzing air quality data alongside health outcomes, the study showed that proximity to heavy traffic corridors is a significant predictor of respiratory health risks, particularly for vulnerable populations such as children. These findings highlight how motor vehicle emissions can contribute to asthma development, supporting the our rationale for investigating transportation factors alongside other predictors like smoking prevalence and EV usage in our project. (4)

## References:
1. World Health Organization. (2021). *WHO global air quality guidelines: Particulate matter (PM2.5 and PM10), ozone, nitrogen dioxide, sulfur dioxide and carbon monoxide*. [https://www.who.int/publications/i/item/9789240034228]
2. U.S. Environmental Protection Agency. (2019). *Integrated science assessment for particulate matter (ISA) (Final report)*. [https://iris.epa.gov/document/%26deid%3D347534]
3. Mattingly, S., Hyun, K. K., Rad, S. K., Arabi, M., & Famili, S. (2019). *Assessing the impact of air pollution on public health along transit routes*. Western Michigan University, Transportation Research Center for Livable Communities. [https://rosap.ntl.bts.gov/view/dot/62326]
4. McConnell, R., Islam, T., Shankardass, K., Jerrett, M., Lurmann, F., Gilliland, F., Peters, J., & Berhane, K. (2010). *Childhood incident asthma and traffic-related air pollution at home and school. Environmental Health Perspectives*. Environmental Health Perspectives, 118(7), 1021–1026. [https://pmc.ncbi.nlm.nih.gov/articles/PMC2920902/]
5. Asthma and Allergy Foundation of America. (2025) *2025 Asthma Capitals: The Most Challenging Places to Live with Asthma*. [https://aafa.org/wp-content/uploads/2025/09/aafa-2025-asthma-capitals-report.pdf]

## Hypothesis

We hypothesize that higher adoption of sustainable transportation (greater public transit and more EV adoption) and lower smoking prevalence are associated with improved air quality in major urban areas. Also, improved air quality is associated with lower rates of asthma-related health outcomes among diagnosed astham patients. 

We further believe that public transportation will exhibit a stronger association with air quality variation across cities than EV adoption and smoking prevalence, given its larger contribution to urban emissions and the capacity to move a lot more people, thus reducing the emissions from less traffic mounting on the majority gasoline-car filled roads. 

We believe using both air quality and asthma rates as good indicators for substantial effects on general health and to try to reduce any latent variables we did not account for separately in each of those two indicators.

## Data

### Data overview

- Dataset #1
  - Dataset Name: Air Quality Statistics by City, 2000-2023
  - Link to the dataset: https://www.epa.gov/air-trends/air-quality-cities-and-counties
  - Number of observations: 1022
  - Number of variables: 27
  - Description of the variables most relevant to this project:  Core Based Statistical Area (this shows the city location), Pollutant (NO2, O3, PM 2.5, PM 10), Trend Statistic (Weighted Annual Mean, Annual Mean, 98th Percentile), Year (2000-2023). 
  - Descriptions of any shortcomings this dataset has with repsect to the project: This dataset measures pollutants with different trend statistics. For instance, NO2 is measured by “Annual Mean”, while PM 2.5 is measured by “Weighted Annual Mean”. The difference in measurement might mean standardizing or further processing of these statistics, or looking at these two pollutants separately. Also, “data from exceptional events are included”, so if there was a wildfire one year for instance in a city, that data is included even though it wouldn’t be an accurate measurement of air quality in general. 

- Dateset #2
  - Dataset Name: San Francisco Registration and Fuel Type Dataset
  - Link to the dataset: https://lab.data.ca.gov/dataset/vehicle-fuel-type-count-by-zip-code
  - Number of observations: ~3,500,000 rows 
  - Number of variables: 7 (date, zip_code, fuel, vehicles, make, model_year, duty)
  - Description of the variables most relevant to this project: date, zip_code, fuel, and vehicles because they are the relevant fields for an analysis of EV registration as a percentage in the San Francisco area. 
  - Descriptions of any shortcomings this dataset has with repsect to the project: Mislabeled files and the 2019 dataset completely does not exist and is actually a late 2018 dataset. Additionally, excessive and some unknown fuel types that need to be filtered to properly analyze the dataset. 

- Dataset #3
  - Dataset Name: Aggregated Smoking & Secondhand Smoke Exposure Dataset
  - Link to the dataset: N/A (compiled from Harris County Community Health Survey, California Health Interview Survey, and NYC Environment & Health Data Portal)
  - Number of observations: 29
  - Number of variables: 6
  - Description of the variables most relevant to this project: Geography (Harris County TX, San Francisco County CA, New York City NY), Year (2003–2024, varies by geography), Metric (Current Smoker % or Secondhand Smoke Exposure at Home – Everyday %), Current_Smoker_Pct (point estimate ranging from 4.7% to 14.6%), and Statistically_Unstable (boolean flag indicating whether the original source marked the estimate as statistically unreliable).
  - Descriptions of any shortcomings this dataset has with respect to the project: The three sources do not measure the same thing, Harris County and San Francisco report current smoker prevalence, while NYC reports secondhand smoke exposure at home (everyday), making direct cross-geography comparisons problematic. Year coverage is also uneven: San Francisco has 18 data points from 2003–2024, Harris County has 8 from 2013–2022 (with no 2018/2019 data), and NYC has only 3 data points (2013, 2014, 2017). Additionally, 4 of the 29 estimates are flagged as statistically unstable, meaning they should be interpreted with caution or excluded from analysis.

We plan to combine these datasets to explore potential relationships between electric vehicle (EV) registration patterns and air quality trends. By aligning the San Francisco vehicle registration data with city-level air quality statistics over the same time periods, we can compare trends and look for correlations. This combined dataset will allow us to visualize changes in EV adoption alongside changes in pollutant levels, and to perform preliminary analyses that may suggest whether increases in EV usage are associated with improvements in air quality. That will be the first factor we check. 

- Dataset #4
    - Dataset Name: Multi-City Longitudinal Asthma Prevalence Dataset (SF, NY, Houston)

    - Link to the dataset: \
         New York: https://a816-dohbesp.nyc.gov/IndicatorPublic/data-explorer/asthma/?id=18#display=summary \
         Houston: https://www.houstontx.gov/planning/Demographics/docs_pdfs/City-Population-Estimates-from-Census-Bureau-2020-to-2022.pdf \
         https://www.houstonstateofhealth.com/indicators/index/view?indicatorId=79&localeId=133891&periodId=246 \
         San Francisco: https://data.chhs.ca.gov/dataset/asthma-prevalence/resource/a440b99b-ccc6-473c-bea1-2baf36b05dbe

    - Number of observations: ~40 (approximate total after expanding SF's 2-year intervals: 20 from NYC, 9 from Houston, 11 from SF).

    - Number of variables: 4

    - Description of the variables most relevant to this project: city (San Francisco, New York City, or Houston), year (the calendar year of data collection, ranging from 2003–2022), age: the demographic filter used for alignment (standardized to adults 18+ years), percentage (percentage of adults reporting a diagnosis and active symptoms or a recent attack).

    - Descriptions of any shortcomings this dataset has with respect to the project: The primary shortcoming is the inconsistency in how "current asthma" is defined and reported across cities. NYC measures adults who had symptoms in the last 12 months, Houston reports adults told they currently have asthma, and SF uses a 2-year pooled estimate of people who still have asthma or had an attack in the last year. This variation in methodology means "8% prevalence" in NYC might not be exactly equivalent to "8% prevalence" in Houston. Additionally, the timeframes are mismatched: NYC provides a deep historical look (starting 2003), while Houston (2014) and SF (2015) have much shorter longitudinal windows. Finally, SF's data required manual expansion from 2-year periods to yearly rows, which assumes the prevalence stayed constant across both years.

In [83]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://data.ca.gov/datastore/dump/d599c3d3-87af-4e8c-8694-9c01f49e3d93',
        'filename': 'vehicle_fuel_2024.csv'},
    { 'url': 'https://data.ca.gov/datastore/dump/d599c3d3-87af-4e8c-8694-9c01f49e3d93',
        'filename': 'vehicle_fuel_2023.csv'},
    { 'url': 'https://data.ca.gov/datastore/dump/9aa5b4c5-252c-4d68-b1be-ffe19a2f1d26',
        'filename': 'vehicle_fuel_2022.csv'},
    { 'url': 'https://data.ca.gov/datastore/dump/888bbb6c-09b4-469c-82e6-1b2a47439736',
        'filename': 'vehicle_fuel_2021.csv'},
    { 'url': 'https://data.ca.gov/datastore/dump/4254a06d-9937-4083-9441-65597dd267e8',
        'filename': 'vehicle_fuel_2020.csv'},
    { 'url': 'https://data.ca.gov/datastore/dump/d304108a-06c1-462f-a144-981dd0109900',
        'filename': 'vehicle_fuel_2018.csv'},
    { 'url': 'https://www.epa.gov/system/files/documents/2024-08/airqualitytrendsbycity2000-2023.xlsx',
        'filename': 'airqualitytrendsbycity.xlsx'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Some important imports before we begin wrangling the data:

In [7]:
import pandas as pd
import numpy as np
import os
from pathlib import Path

### Air Quality Data

This dataset looks at air pollution trends in U.S. cities (called Core Based Statistical Areas, or CBSAs) from 2000 to 2023. Each entry shows a pollutant measured in a specific city along with a statistic that summarizes how that pollutant is evaluated. For instance, one major metric is ozone (O3), which is reported using the “4th Max” value — meaning the fourth-highest daily 8-hour ozone level in a year. This is used instead of the highest reading so that one unusual day doesn't distort the data. The values are around 0.06–0.10 parts per million (ppm). Ozone can irritate the lungs, trigger asthma attacks, and make it harder for people to breathe. Ozone values > 0.07 ppm is considered harmful to breathing, and especially for those with asthma. Ozone values > 0.08 is harmful for everyone, and > 0.3 means reduction in lung function and chest pain. 

Another metric important to our question is PM 2.5. PM 2.5 values are measured in micrograms per cubic meter (µg/m^3). The “Weighted Annual Mean” represents the average exposure throughout the year. Some cities had averages above 15 µg/m³ in the early 2000s, but many are closer to about 7–10 in recent years. This matters because long-term exposure to PM2.5 is strongly linked to heart disease, lung cancer, and other health problems. 0-12 µg/m^3 is considered satisfactory, 12.1-13.4 µg/m^3 moderate but not good for sensitve people, and > 35 is unhealthy/hazardous. 

There are a few concerns with this dataset. Firstly, the file notes that the EPA found data quality issues affecting some states, including Florida, Illinois, most of Tennessee, and parts of Kentucky. Measurements from those areas may not be fully reliable. Also, cities have different numbers of monitoring stations, so the data could be not consistent between cities. Another limitation is that the dataset relies on summary statistics rather than raw daily readings. While this makes it easier to see long-term trends, it can hide short-term spikes such as wildfire smoke events.

In [ ]:
# 1. load dataset
air = pd.read_excel('data/00-raw/airqualitytrendsbycity.xlsx',
                    header=3)

print(air.columns.tolist())

# 2. make dataset tidy
air = air.iloc[3:].reset_index(drop=True) # drop metadata
# fill grouped labels
air["Core Based Statistical Area"] = air["Core Based Statistical Area"].ffill()
air = air.rename(columns={
    "Core Based Statistical Area":"cbsa",
    "Pollutant":"pollutant",
    "Trend Statistic":"trend_stat",
    "Number of Trends Sites":"sites"
})
#dataset has each year in it's own column, but 
#each variable should have it's own column while years should be stored in a single 'year' column
years = [c for c in air.columns if str(c).isdigit()]
air[years] = air[years].apply(pd.to_numeric, errors='coerce')

air = air.melt(
    id_vars=["cbsa","pollutant","trend_stat","sites"],
    value_vars=years,
    var_name="year",
    value_name="value"
)

#3. demonstrate size of data
print("Shape of data:", air.shape)

#4. find out how much data is missing
print("Missing data: \n", air.isna().sum())
print("\nMissing %:", air["value"].isna().mean()*100)

Less than 1% of the data is missing, and it seems to be from earlier years, which suggests that some cities didn't have monitoring stations yet.

In [ ]:
#5. find outliers

def find_outliers(df):
    q1 = df.value.quantile(.25)
    q3 = df.value.quantile(.75)
    iqr = q3-q1
    return df[(df.value < q1-1.5*iqr) | (df.value > q3+1.5*iqr)]

outliers = air.groupby("pollutant")[air.columns].apply(find_outliers)

print("Outliers found:", len(outliers))

In [ ]:
# 6. clean the data

air = air.dropna(subset=["pollutant", "cbsa"])
print(air.isna().sum())  
air.head()

In [ ]:
# 7. load data into data/01-interim
os.makedirs("data/01-interim", exist_ok=True)

air.to_csv("data/01-interim/air_quality_tidy.csv", index=False)

### San Francisco Registration and Fuel Dataset

This dataset contains counts of vehicle registrations in California by zip code and fuel type, covering the years 2018 through 2024, excluding 2019. The key metrics are:

- **Date**: the date (month/day/year) the vehicle was registered.
- **Zip Code**: the 5-digit numeric code representing the geographic area where the vehicle was registered.
- **Model** Year: the year the vehicle model was manufactured. This can sometimes be represented with ranges in case the exact same vehicle model was manufactured for multiple years.
- **Fuel**: the fuel type the vehicle utilizes.
- **Make**: the manufacturer of the vehicle.
- **Duty**: the duty type (heavy or light) of the vehicle.
- **Vehicles**: the number of vehicles corresponding to those attributes (date, zip code, model year, etc.). These values can range from 1 to several thousand per row.

**Note**: Some dataset labels do not match the actual registration dates. For example, the file labeled 2019 contained late 2018 registrations and no 2019 registrations. Moreover, the links labeled for 2023, 2024, and 2025 actually linked to the previous year's file and the 2022 dataset had both the 2023 and 2022 links directing to it. These discrepancies are noted here for transparency before analysis and directly reported to the official California Open Data portal.

In [ ]:
# files to be parsed for San Francisco registration data
sf_ev_files = [
    'data/00-raw/vehicle_fuel_2018.csv',
    'data/00-raw/vehicle_fuel_2020.csv',
    'data/00-raw/vehicle_fuel_2021.csv',
    'data/00-raw/vehicle_fuel_2022.csv',
    'data/00-raw/vehicle_fuel_2023.csv',
    'data/00-raw/vehicle_fuel_2024.csv'
]

# creating a single dataframe to combine all the datasets
sf_ev_dfs = []

for file in sf_ev_files:
    df = pd.read_csv(file, low_memory=False)
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
    # standardizing the columns so that they uniform across the different datasets
    sf_ev_dfs.append(df)

sf_ev_data = pd.concat(sf_ev_dfs, ignore_index=True)

# dropping the id column the imported csv contain for clarity
if '_id' in sf_ev_data.columns:
    sf_ev_data = sf_ev_data.drop(columns=['_id'])

In [ ]:
# shape and size of the dataset before any manipulation
print("Dataset shape: ", sf_ev_data.shape)
print("Entries: ", sf_ev_data.size)
sf_ev_data

The key columns we will focus on for analysis are date, zip_code, fuel, and vehicles. These columns contain critical information needed to examine vehicle registrations by year, location, fuel type, and count. The remaining columns are irrelevant because even if they contain missing values, they have no effect on the attributes we are analyzing, so we can safely ignore them.

Because our analysis relies on complete and accurate information for these key columns, any rows containing missing or unknown data are removed. This ensures our dataset is clean and fully reliable for analysis later on.

In [ ]:
# keep only key columns
sf_ev_clean_data = sf_ev_data[['date', 'zip_code', 'fuel', 'vehicles']].copy()

# drop rows where vehicles is missing or <= 0
sf_ev_clean_data = sf_ev_clean_data.dropna(subset=['vehicles'])
sf_ev_clean_data = sf_ev_clean_data[sf_ev_clean_data['vehicles'] > 0]

# ensure zip_code and fuel are strings
sf_ev_clean_data['zip_code'] = sf_ev_clean_data['zip_code'].astype(str)
sf_ev_clean_data['fuel'] = sf_ev_clean_data['fuel'].astype(str)

# strip spaces and lower-case
sf_ev_clean_data['zip_code'] = sf_ev_clean_data['zip_code'].str.strip().str.lower()
sf_ev_clean_data['fuel'] = sf_ev_clean_data['fuel'].str.strip().str.lower()

# remove unknown / other values
unk_values = ['unk', 'unknown', 'other', '']
sf_ev_clean_data = sf_ev_clean_data[
    ~sf_ev_clean_data['zip_code'].isin(unk_values) &
    ~sf_ev_clean_data['fuel'].isin(unk_values)
]

In [ ]:
sf_ev_clean_data

Now that we have cleaned our dataset, we can begin standardizing it to fit our analysis needs.

Extract the year from date: The date column contains full registration date, which is more detailed than necessary for our anaylsis. We will extract the year and replace the date with that.

Filtering for San Francisco zip codes: This analysis focuses specifically on San Francisco, so we will filter the dataset to include only relevant zip codes. San Francisco zip codes generally begin with 941, which allows for an easy way to filter the dataset.

Standardizing fuel types: The dataset contains many specific fuel types, some of which are rare or hybrids, so we can standardize them into broader categories such as Gasoline, Diesel, Electric, and Hybrid.

Combining the vehicle counts: Now we can combine all the vehicle counts into their respective fuel type, year, and location to get rid of duplicates or ambiguity in the rows.

In [ ]:
# extracting the year from date and renaming the column
sf_ev_clean_data['date'] = pd.to_datetime(sf_ev_clean_data['date'])
sf_ev_clean_data['year'] = sf_ev_clean_data['date'].dt.year
sf_ev_clean_data = sf_ev_clean_data.drop(columns=['date'])

# filtering for San Francisco zip codes
sf_ev_clean_data = sf_ev_clean_data[sf_ev_clean_data['zip_code'].str.startswith('941')]

# function to standardize the fuel types
def standardize_fuel(fuel):
    fuel = fuel.strip().lower()
    if fuel in ['gasoline', 'flex-fuel', 'natural gas']:
        return 'Gasoline'
    elif fuel == 'diesel and diesel hybrid':
        return 'Diesel'
    elif fuel in ['battery electric', 'hydrogen fuel cell']:
        return 'Electric'
    elif fuel in ['plug-in hybrid', 'hybrid gasoline']:
        return 'Hybrid'
    else:
        return 'Other'

sf_ev_clean_data['fuel'] = sf_ev_clean_data['fuel'].apply(standardize_fuel)

sf_ev_clean_data = (
    sf_ev_clean_data
    .groupby(['year', 'zip_code', 'fuel'], as_index=False)
    .agg({'vehicles': 'sum'})
)

In [ ]:
print("Dataset shape: ", sf_ev_clean_data.shape)
print("Entries: ", sf_ev_clean_data.size)
sf_ev_clean_data

And finally, we can save this clean and tidy dataset to 02-processed:

In [ ]:
processed_path = 'data/02-processed/'
os.makedirs(processed_path, exist_ok=True)

# save the cleaned dataset
sf_ev_clean_data.to_csv(processed_path + 'sf_vehicle_fuel_data_processed.csv', index=False)

### Dataset #3

### Aggregated Smoking & Secondhand Smoke Exposure Dataset

This dataset was compiled from three separate public health surveys to track smoking-related metrics across three U.S. cities: Harris County (TX), San Francisco County (CA), and New York City (NY). It covers years ranging from 2003 to 2024, though the time coverage varies significantly by geography.
The primary metric across most of the dataset is current smoker prevalence (%), the share of adults who reported being a current smoker at the time of the survey. For Harris County, this comes from the Harris County Community Health Survey and covers 2013–2022 (with gaps in 2018 and 2019). For San Francisco, this comes from the California Health Interview Survey (CHIS) and is the most complete series, spanning 2003–2024 with 18 data points. Values across both geographies range from about 4.7% to 14.6%, reflecting a general downward trend in smoking rates over time.

The New York City data is the exception: rather than current smoker prevalence, it measures secondhand smoke exposure at home (everyday %) — the share of adults who reported being exposed to secondhand smoke in their home every day. This comes from the NYC Environment & Health Data Portal and covers only three survey years (2013, 2014, and 2017), with values around 9–11%.

There are a few important limitations to keep in mind. The most significant is that the NYC metric is fundamentally different from the other two, secondhand smoke exposure is not the same as smoking prevalence, so NYC cannot be directly compared to Harris County or San Francisco without additional context or caveats. Year coverage is also uneven, with NYC having far fewer data points than the other two geographies, limiting any time-trend analysis for that city. Finally, 4 of the 29 estimates are flagged as statistically unstable by their original sources, meaning the sample sizes behind those estimates were small enough that the values should be interpreted with caution. This is something that will need to be considered when doing our data analysis and will have to be fixed by using another data set or accounting for these shortcomings.

In [ ]:
"""
Combines three smoking-related datasets into a single long-format CSV.

Sources:
  1. adults-who-smoke.csv           – Harris County, TX current smoker %
  2. AskCHISResults*.csv            – San Francisco County CHIS current smoker %
  3. NYC_EH_Data_Portal_*.csv       – NYC citywide secondhand smoke exposure %

Output: combined_smoking_data.csv
"""

import pandas as pd
import re

# ── 1. Harris County ──────────────────────────────────────────────────────────
harris = pd.read_csv('data/00-raw/adults-who-smoke.csv', encoding='utf-8-sig')
harris.columns = ['Year', 'Current_Smoker_Pct']
harris['Year'] = harris['Year'].astype(int)
harris['Geography'] = 'Harris County, TX'
harris['Source'] = 'Harris County CHS'
harris['Metric'] = 'Current Smoker (%)'
harris['Statistically_Unstable'] = False
harris = harris[['Year','Geography','Source','Metric','Current_Smoker_Pct','Statistically_Unstable']]

The date column contains full registration dates (MM/DD/YYYY). Since our analysis focuses on year-over-year trends, we extract just the year.

In [ ]:
# ── 2. San Francisco County ───────────────────────────────────────────
# parse excel into csv style
san_fran_raw = pd.read_excel('data/00-raw/AskCHISResults202602191325.csv', header=None)
san_fran_data = san_fran_raw.iloc[7:25, [0, 1]].copy()
san_fran_data.columns = ['Label', 'Pct']
san_fran_data = san_fran_data[san_fran_data['Label'].str.contains('Current Smoker', na=False)]

def parse_san_fran(label, pct):
    year = int(re.search(r'\((\d{4})\)', str(label)).group(1))
    unstable = '*' in str(pct)
    pct_val = float(re.sub(r'[^\d.]', '', str(pct)))
    return year, pct_val, unstable

rows = [parse_san_fran(r['Label'], r['Pct']) for _, r in san_fran_data.iterrows()]
san_fran = pd.DataFrame(rows, columns=['Year','Current_Smoker_Pct','Statistically_Unstable'])
san_fran['Geography'] = 'San Francisco County, CA'
san_fran['Source'] = 'CA Health Interview Survey (CHIS)'
san_fran['Metric'] = 'Current Smoker (%)'
san_fran = san_fran[['Year','Geography','Source','Metric','Current_Smoker_Pct','Statistically_Unstable']]

The NYC data is structured differently from the other two sources — it is stored as a proper CSV and requires filtering to citywide-level rows only (as opposed to borough or neighborhood-level). We also parse the `Everyday (percent)` column, which contains confidence intervals embedded in the string alongside the point estimate, so we extract just the numeric value and flag any statistically unstable estimates.

In [ ]:
# ── 3. NYC Secondhand Smoke (Citywide rows only) ──────────────────────────────
nyc_raw = pd.read_csv('data/00-raw/NYC EH Data Portal - Secondhand smoke at home (from outside sources) (full table).csv')
nyc_city = nyc_raw[nyc_raw['GeoType'] == 'Citywide'].copy().reset_index(drop=True)

def parse_nyc(val):
    s = str(val)
    unstable = '*' in s
    m = re.search(r'[\d.]+', s)
    pct = float(m.group()) if m else None
    return pct, unstable

nyc_pcts, nyc_unstable = [], []
for v in nyc_city['Everyday (percent)']:
    p, u = parse_nyc(v)
    nyc_pcts.append(p)
    nyc_unstable.append(u)

nyc = pd.DataFrame({
    'Year': nyc_city['TimePeriod'].astype(int),
    'Geography': 'New York City, NY',
    'Source': 'NYC EH Data Portal',
    'Metric': 'Secondhand Smoke Exposure at Home – Everyday (%)',
    'Current_Smoker_Pct': nyc_pcts,
    'Statistically_Unstable': nyc_unstable,
})

In [ ]:
combined = pd.concat([harris, san_fran, nyc], ignore_index=True)
combined = combined.sort_values(['Geography', 'Year']).reset_index(drop=True)
combined.to_csv('data/01-interim/combined_smoking_data.csv', index=False)

With all three sources now aggregated into a single file, we load the combined dataset and perform some final processing steps. This includes removing any statistically unstable estimates flagged during aggregation, as well as dropping any rows with missing values that could skew our analysis.

In [ ]:
import pandas as pd

# Load the combined dataset
df = pd.read_csv('data/01-interim/combined_smoking_data.csv')

# Remove statistically unstable estimates and rows with missing values
df = df[df['Statistically_Unstable'] == False].dropna().reset_index(drop=True)

# Save cleaned dataset to processed
df.to_csv('data/02-processed/combined_smoking_data_clean.csv', index=False)

print(f"Rows after processing: {len(df)}")
df.head()

### New York Asthma Dataset

This is the dataset of adults(18+) reporting an asthma diagnosis, and symptoms, in the last 12 months (from when they were surveyed) in New York city. The data collected for this dataset include the following areas in New York city: the Bronx, Manhattan, Brooklyn, Staten Island, and Queens. It includes the number of population and percentage of reported adults from 2003-2022, and the data is collected per year.
- **TimePeriod**: the year the data is collected
- **GeoTypeDesc**: citywide or borough for different areas.
- **GeoID**: the id used by the source to identify 1: citywide and Bronx, 2: Brooklyn, 3: Manhattan, 4: Queens, 5: Staten Island.
- **BoroID**: the ID for only the borough, 1: Bronx, 2: Brooklyn, 3: Manhattan, 4: Queens, 5: Staten Island.
- **Geography**: text data including the following different regions: New York City wide, Bronx, Brooklyn, Manhattan, Queens, Staten Island.
- **Area**: the same as Geography.
- **Number**: estimated number of adults aged 18 years and older who reported medically diagnosed asthma and symptoms in the last 12 months, rounded to the nearest 1,000. Beginning in 2017, indicator includes data imputed for missing responses.
- **Percent**: estimated number of adults aged 18 years and older who reported medically diagnosed asthma with symptoms in the last 12 months, divided by all adults; expressed as percent. Beginning in 2017, indicator includes data imputed for missing responses.
- **Age-adjusted percent**: estimated number of adults aged 18 years and older who reported medically diagnosed asthma with symptoms in the last 12 months, divided by all adults and adjusted for age; expressed as percent. Beginning in 2017, indicator includes data imputed for missing responses.

### Houston Asthma Dataset

This is the dataset of an indicator showing the percentage of adults(18+) who have been told by a health care provider that they currently have asthma in Houston city. It includes the number of population and percentage of reported adults from 2014-2022, and the data is collected per year.
- **year**: the year the data is collected
- **population**: the population of Houston city documented by the Planning and Development Department of Houston.
- **percentage**: the percentage of adults in Houston who are diagonosed with asthma.
- **number**: the number of people with asthma (the product of the percentage and the population).

### San Francisco Asthma Dataset

This is the CHIS Data-Current Asthma Prevalence by County 2015-Present dataset. This dataset contains current asthma prevalence, the estimated percentage of Californians who have ever been diagnosed with asthma by a health care provider AND report they still have asthma and/or had an asthma episode or attack within the past 12 months, statewide and by county. The data are stratified by age group (all ages, 0-17, 18+, 0-4, 5-17, 18-64, 65+) and reported for 2-year periods. These data are derived from the California Health Interview Survey (CHIS).

- **County**: the county of residence
- **Years**: 2-year period during which survey data were collected
- **Strata**: general demographic category under which responses have been stratified
- **Age Group**: all ages, 0-17 years, 18+ years, 0-4 years, 5-17 years, 18-64 years, and 65+ years
- **Current Prevalence**: estimate of the percentage of people who report that they have ever been diagnosed with asthma AND that they still have asthma at the time of the survey (source: CHIS)
- **95% Confidence Interval**: the current prevalence estimate is calculated from survey respondents (who represent a sample of the population) and may not reflect the true current prevalence for the entire population. This 95% confidence interval is the range of values which contains the popuation's actual current prevalence with 95% certainty
- **Counties Grouped**: counties combined for analysis
- **Comment**: warning provided when prevalence estimate is statistically unstable (standard error is 30-50% of prevalence estimate). Data suppressed when standard error exceeds 50% of prevalence estimate

In [68]:
# load the file from directory
ny_asthma_data = 'data/00-raw/NYC EH Data Portal - Adults with a recent asthma attack (filtered).csv'

df = pd.read_csv(ny_asthma_data)
# to keep only data for New York City
new_df = df[df['Geography']=='New York City']

new_df = new_df.rename(columns={
    "TimePeriod":"year",
    "GeoTypeDesc":"geotype",
    "GeoID":"geoID",
    "GeoRank":"geoRank",
    "BoroID":"boroID",
    "Borough":"borough",
    "Geography":"geography",
    "Area":"area",
    "Number":"number",
    "Percent":"percentage",
    "Age-adjusted percent":"agePercent"
})

# keep only relevant columns
new_df = new_df.drop(['geotype', 'geoID', 'geoRank', 'boroID', 'borough', 'geography', 
                      'area', 'agePercent', 'number'], axis=1)

# This pattern looks for: (digits + decimal + digits) OR (just digits)
new_df['percentage'] = new_df['percentage'].astype(str).str.extract(r'(\d+\.\d+|\d+)').astype(float)
print(new_df.dtypes)
new_df['city'] = 'new york'

new_df

year            int64
percentage    float64
dtype: object

     year  percentage      city
0    2022         4.3  new york
6    2021         4.9  new york
12   2020         3.8  new york
18   2019         4.5  new york
24   2018         4.4  new york
30   2017         4.4  new york
36   2016         4.8  new york
42   2015         6.0  new york
48   2014         3.7  new york
54   2013         3.9  new york
60   2012         4.6  new york
66   2011         4.5  new york
72   2010         3.7  new york
78   2009         4.1  new york
84   2008         5.3  new york
90   2007         4.4  new york
96   2006         5.3  new york
102  2004         4.9  new york
108  2003         4.6  new york

In [72]:
# load the file from directory
ht_asthma_data = 'data/00-raw/Texas_Adults_With_Current_Asthma.xlsx'

ht_df = pd.read_excel(ht_asthma_data)
ht_df['city'] = 'houston'
ht_df['percentage'] = ht_df['percentage']*100
ht_df = ht_df.drop(['population', 'number'], axis=1)
ht_df

   year  percentage     city
0  2014         8.5  houston
1  2015         8.8  houston
2  2016         8.8  houston
3  2017         8.3  houston
4  2018         9.0  houston
5  2019         8.8  houston
6  2020         9.1  houston
7  2021        10.0  houston
8  2022         9.3  houston

In [79]:
import requests
import io

# URL (CSV format)
sf_asthma_url = "https://data.chhs.ca.gov/dataset/01f456c3-db34-44f2-a52c-6811bef8ba6d/resource/a440b99b-ccc6-473c-bea1-2baf36b05dbe/download/current-asthma-prevalence-by-county-2015_2022.csv"
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(sf_asthma_url, headers=headers)

if response.status_code == 200:
    # ADD encoding='ISO-8859-1' OR encoding='cp1252'
    sf_df = pd.read_csv(io.BytesIO(response.content), encoding='ISO-8859-1')
    sf_df = sf_df.drop(['STRATA', '95% CONFIDENCE INTERVAL', 'COUNTIES GROUPED', 'COMMENT'], axis=1)

    sf_df = sf_df.rename(columns={'COUNTY':'city', 'YEARS':'year', 'AGE GROUP':'age', 'CURRENT PREVALENCE':'percentage'})
    sf_df = sf_df[sf_df['city']=='San Francisco']
    sf_df = sf_df[sf_df['age']=='18+ years']
    sf_df['city'] = 'san francisco'
    sf_df = sf_df.reset_index(drop=False)
    
    sf_df.loc[sf_df['year'].str.contains('2015'), 'year'] = '2015'
    sf_df.loc[sf_df['year'].str.contains('2017'), 'year'] = '2017'
    sf_df.loc[sf_df['year'].str.contains('2019'), 'year'] = '2019'
    sf_df.loc[sf_df['year'].str.contains('2021'), 'year'] = '2021'

    # Using the trick from before to just take the first 4 characters
    sf_df['year'] = sf_df['year'].str[:4].astype(int)
    
    # Create a copy of the dataframe to represent the "even" years
    even_years_df = sf_df.copy()
    
    # Add 1 to the year column (e.g., 2015 becomes 2016)
    even_years_df['year'] = even_years_df['year'] + 1
    
    # Combine the original "odd" years with the new "even" years
    sf_df = pd.concat([sf_df, even_years_df])
    
    # Sort by year so it's chronological and reset the index
    sf_df = sf_df.sort_values('year').reset_index(drop=True)
    sf_df = sf_df.drop(['index','age'], axis=1)
else:
    print(f"Failed to download. Status code: {response.status_code}")

sf_df

            city  year  percentage
0  san francisco  2015         9.1
1  san francisco  2016         9.1
2  san francisco  2017         7.7
3  san francisco  2018         7.7
4  san francisco  2019         8.0
5  san francisco  2020         8.0
6  san francisco  2021         8.8
7  san francisco  2022         8.8

In [81]:
asthma_df = pd.concat([sf_df, new_df, ht_df], ignore_index=True)

# Sort by year for sanity
asthma_df = asthma_df.sort_values('year')
asthma_df = asthma_df.reset_index(drop=False)
asthma_df = asthma_df.drop('index', axis=1)
asthma_df

             city  year  percentage
0        new york  2003         4.6
1        new york  2004         4.9
2        new york  2006         5.3
3        new york  2007         4.4
4        new york  2008         5.3
5        new york  2009         4.1
6        new york  2010         3.7
7        new york  2011         4.5
8        new york  2012         4.6
9        new york  2013         3.9
10        houston  2014         8.5
11       new york  2014         3.7
12        houston  2015         8.8
13       new york  2015         6.0
14  san francisco  2015         9.1
15        houston  2016         8.8
16  san francisco  2016         9.1
17       new york  2016         4.8
18       new york  2017         4.4
19        houston  2017         8.3
20  san francisco  2017         7.7
21       new york  2018         4.4
22        houston  2018         9.0
23  san francisco  2018         7.7
24        houston  2019         8.8
25  san francisco  2019         8.0
26       new york  2019         4.5
27       new york  2020         3.8
28        houston  2020         9.1
29  san francisco  2020         8.0
30  san francisco  2021         8.8
31       new york  2021         4.9
32        houston  2021        10.0
33  san francisco  2022         8.8
34       new york  2022         4.3
35        houston  2022         9.3

## Ethics 

### A. Data Collection
 - [X] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?

> This project relies on aggregated, city-level secondary data (e.g., transportation usage, smoking rates, EV adoption, air quality metrics) rather than individual-level human subject data. Because we are not directly collecting data from individuals, informed consent is not applicable in the traditional sense. However, we acknowledge that the original data sources may have their own consent limitations, and we rely only on publicly available or ethically collected datasets.

 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?

> There are several sources of potential collection bias in this dataset. Large cities differ significantly in transportation budgets, population density, and infrastructure, which affects public transportation usage, EV adoption, and driving behavior. Denser cities may naturally rely less on private vehicles, while smoking rates may be influenced by density-related stressors or local social norms. Income-related bias is also present, as wealthier populations are more likely to own EVs and rely less on public transportation, while lower-income groups may experience higher stressors, higher smoking rates, and greater exposure to pollution. Cultural and regulatory differences (such as smoking bans or EV incentives) further bias how data is collected and reported across cities.

 - [ ] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?
 - [X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

> While individual protected attributes such as race or gender are not directly included, we acknowledge that variables like income, age, transportation access, and neighborhood-level pollution can act as proxies for protected groups. We explicitly consider these limitations and design the analysis to test outcomes across income levels and city characteristics to help identify potential downstream bias.

### B. Data Storage
 - [X] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?

> All datasets are stored locally or in secure cloud-based academic environments with restricted access. Because the data is aggregated and non-PII, security risks are limited, but standard access controls and version management are still used.

 - [ ] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?
 - [X] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

> Data will be retained only for the duration of the project and any required academic review period. Afterward, datasets and derived files can be deleted or archived in anonymized form.

### C. Analysis
 - [X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?

> We recognize that quantitative city-level data may miss lived experiences of communities most affected by asthma and lung disease, particularly lower-income populations. To reduce this blind spot, we explicitly question assumptions in the analysis and acknowledge that statistical relationships may not fully capture structural or social factors influencing health outcomes.

 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?

> We examine the dataset for imbalances, missing data, and uneven representation across cities and income groups. Confounding variables such as population density, transportation budgets, walkability, factory presence, median income, car ownership rates, smoking regulations, and EV incentives are explicitly considered to avoid overstating causal claims.

 - [X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?

> Visualizations and summary statistics are designed to reflect proportional differences across cities without exaggerating effects. We avoid specifically picking comparisons and clearly label axes, scales, and assumptions.

 - [ ] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?
 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

> The analysis process is documented step by step, including data sources, preprocessing decisions, and modeling assumptions, allowing results to be reproduced and reviewed if issues are identified later.

### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?

> We acknowledge that variables such as income, transportation access, and neighborhood pollution may act as proxies for protected characteristics. These variables are included carefully and interpreted cautiously to avoid reinforcing harmful stereotypes or implying individual-level causation.

 - [X] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?

> Model outputs are compared across income levels and city characteristics to check for systematic differences that could indicate unfair or biased outcomes.

 - [X] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?

> We consider multiple evaluation metrics rather than optimizing a single outcome, recognizing that focusing on one metric could obscure harms to certain groups.

 - [X] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?

> The model and its results are kept interpretable, allowing us to explain in plain language how variables such as air quality, transportation patterns, and smoking rates relate to asthma outcomes.

 - [X] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

> We clearly communicate that correlations identified in the model do not imply causation and that remaining biases and confounders may still influence results.

### E. Deployment
 - [ ] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
 - [ ] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
 - [ ] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
 - [X] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?

> We acknowledge the risk that findings could be misused to oversimplify health disparities or place blame on certain populations. To mitigate this, we explicitly frame results as descriptive and exploratory and emphasize structural, environmental, and policy-related factors rather than individual behavior alone.

## Team Expectations

* *Use google chat to communicate, making sure to respond within 8 hours. Meet once a week hybrid and communicate if you can’t make it*
* *Use a straightforward tone but be a polite and respect people’s opinions*
* *We will make decisions unanimously, if someone isn’t responding those who are there can make the decision*
* *Assign things based on what people want to do every meeting, have meeting notes on what tasks people are doing, communicate on google chat if you change something on the repo.*
* *We will meet on Tuesdays and do a virtual check in on Saturdays to see how people are doing with their tasks.*
* *If someone is struggling, we will openly communicate with them. If you’re assigned a task and not able to make it, communicate with the group within 2 days of the deadline*
* *We put it in google chat.*

## Project Timeline Proposal

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 1/27  |  5 PM | Look through past COGS 108 projects. | Research question and topic, go through past COGS 108 projects together, discuss takeaways from them  | 
| 2/3  |  2 PM |  Do background research on topic, look at other people's research on topic | Discuss ideal dataset(s) and ethics; draft project proposal | 
| 2/10  | 5 PM  | Start finding datasets for research question  | Decide which datasets would fit our question/how we would use it, and submit Checkpoint 1  |
| 2/18  | 5:30 PM  | Start organizing data/cleaning data | Cleaning/combining and wrangling of datasets   |
| 2/24  | 5 PM  | Start data analysis and visualization | Finish cleaning, continue data analysis and visualization together |
| 3/3  | 5 PM  | Finish up data analysis and visualization | Go through all our results and submit Checkpoint #2 together |
| 3/10  | Before 11:59 PM  | Finalize all portions of project | Record video and turn in Final Project & Group Project Surveys |